<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<WasmBuildNative>true</WasmBuildNative>
	  <UserSecretsId>19b1d2fa-5291-45ba-b76d-2ccce5b878f6</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.3" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.19" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
